import { createFileRoute, Link } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { motion } from "framer-motion";
import { Search, ArrowRight, MapPin } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { PlatformNav } from "@/components/platform/PlatformNav";
import { PlatformFooter } from "@/components/platform/PlatformFooter";
import type { Clinic } from "@/lib/clinic-types";

export const Route = createFileRoute("/explore")({
  head: () => ({
    meta: [
      { title: "Explore live clinic experiences — TechAI Labs" },
      { name: "description", content: "Browse demo dental clinic websites generated by the TechAI Labs engine." },
    ],
  }),
  component: ExplorePage,
});

function ExplorePage() {
  const [clinics, setClinics] = useState<Clinic[]>([]);
  const [q, setQ] = useState("");
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    supabase
      .from("clinics")
      .select("*")
      .order("created_at", { ascending: false })
      .limit(60)
      .then(({ data }) => {
        setClinics((data as unknown as Clinic[]) ?? []);
        setLoading(false);
      });
  }, []);

  const filtered = clinics.filter(
    (c) =>
      !q ||
      c.clinic_name.toLowerCase().includes(q.toLowerCase()) ||
      c.city.toLowerCase().includes(q.toLowerCase()),
  );

  return (
    <div className="min-h-screen bg-background">
      <PlatformNav />
      <section className="relative overflow-hidden border-b border-border/60">
        <div className="absolute inset-0 bg-aurora opacity-50" />
        <div className="relative mx-auto max-w-7xl px-6 py-20">
          <span className="inline-flex items-center gap-2 rounded-full border border-border/60 bg-background/40 px-3 py-1 text-xs font-medium text-muted-foreground backdrop-blur">
            <span className="h-1.5 w-1.5 rounded-full bg-[oklch(0.78_0.18_290)]" /> Marketplace
          </span>
          <h1 className="mt-4 font-display text-5xl tracking-tight">Explore clinic experiences</h1>
          <p className="mt-3 max-w-xl text-muted-foreground">
            Each clinic below is rendered from the same engine. Customise, claim, or use as a starting point.
          </p>
          <div className="mt-8 flex max-w-md items-center gap-2 rounded-xl border border-border/70 bg-background/60 px-4 py-3 backdrop-blur focus-within:border-foreground/40">
            <Search className="h-4 w-4 text-muted-foreground" />
            <input
              value={q}
              onChange={(e) => setQ(e.target.value)}
              placeholder="Search by name or city"
              className="w-full bg-transparent text-sm normal-case tracking-normal outline-none placeholder:text-muted-foreground"
            />
          </div>
        </div>
      </section>

      <section className="mx-auto max-w-7xl px-6 py-16">
        {loading ? (
          <p className="text-muted-foreground">Loading…</p>
        ) : filtered.length === 0 ? (
          <p className="text-muted-foreground">No clinics yet. Add some in the admin console.</p>
        ) : (
          <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
            {filtered.map((c, i) => (
              <motion.div
                key={c.id}
                initial={{ opacity: 0, y: 12 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: Math.min(i * 0.04, 0.4) }}
              >
                <Link
                  to="/clinic/$slug"
                  params={{ slug: c.slug }}
                  className="group block overflow-hidden rounded-2xl border border-border/70 bg-surface transition hover:border-foreground/30"
                >
                  <div
                    className="relative h-40 overflow-hidden"
                    style={{
                      background: `linear-gradient(135deg, ${c.primary_color}, ${c.secondary_color})`,
                    }}
                  >
                    <div className="absolute inset-0 bg-grid opacity-30" />
                    <div className="absolute bottom-3 left-4 right-4 flex items-end justify-between text-white/90">
                      <p className="font-display text-2xl drop-shadow">{c.clinic_name}</p>
                      <span className="rounded-full bg-black/30 px-2 py-0.5 text-[11px] backdrop-blur">
                        Dental
                      </span>
                    </div>
                  </div>
                  <div className="p-5">
                    <div className="flex items-center gap-1.5 text-xs text-muted-foreground">
                      <MapPin className="h-3.5 w-3.5" /> {c.city}, {c.country_code ?? c.country}
                    </div>
                    <p className="mt-2 line-clamp-2 text-sm text-muted-foreground">{c.tagline}</p>
                    <div className="mt-4 flex items-center justify-between text-xs">
                      <span className="text-muted-foreground">
                        ★ {Number(c.rating).toFixed(1)} · {c.review_count} reviews
                      </span>
                      <span className="inline-flex items-center gap-1 text-foreground">
                        Open <ArrowRight className="h-3 w-3 transition group-hover:translate-x-0.5" />
                      </span>
                    </div>
                  </div>
                </Link>
              </motion.div>
            ))}
          </div>
        )}
      </section>
      <PlatformFooter />
    </div>
  );
}
