/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ClinicSlugRouteImport } from './routes/clinic/$slug'
import { Route as AdminThemesRouteImport } from './routes/admin/themes'
import { Route as AdminImportRouteImport } from './routes/admin/import'
import { Route as AdminClinicsRouteImport } from './routes/admin/clinics'
import { Route as AdminClaimsRouteImport } from './routes/admin/claims'
import { Route as ClinicSlugIndexRouteImport } from './routes/clinic/$slug/index'
import { Route as ClinicSlugSmileCheckRouteImport } from './routes/clinic/$slug/smile-check'
import { Route as ClinicSlugServicesRouteImport } from './routes/clinic/$slug/services'
import { Route as ClinicSlugReviewsRouteImport } from './routes/clinic/$slug/reviews'
import { Route as ClinicSlugGalleryRouteImport } from './routes/clinic/$slug/gallery'
import { Route as ClinicSlugFaqRouteImport } from './routes/clinic/$slug/faq'
import { Route as ClinicSlugContactRouteImport } from './routes/clinic/$slug/contact'
import { Route as ClinicSlugAboutRouteImport } from './routes/clinic/$slug/about'
import { Route as ClinicSlugServicesServiceSlugRouteImport } from './routes/clinic/$slug/services.$serviceSlug'

const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ClinicSlugRoute = ClinicSlugRouteImport.update({
  id: '/clinic/$slug',
  path: '/clinic/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminThemesRoute = AdminThemesRouteImport.update({
  id: '/themes',
  path: '/themes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminImportRoute = AdminImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClinicsRoute = AdminClinicsRouteImport.update({
  id: '/clinics',
  path: '/clinics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClaimsRoute = AdminClaimsRouteImport.update({
  id: '/claims',
  path: '/claims',
  getParentRoute: () => AdminRoute,
} as any)
const ClinicSlugIndexRoute = ClinicSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClinicSlugRoute,
} as any)
const ClinicSlugSmileCheckRoute = ClinicSlugSmileCheckRouteImport.update({
  id: '/smile-check',
  path: '/smile-check',
  getParentRoute: () => ClinicSlugRoute,
} as any)
const ClinicSlugServicesRoute = ClinicSlugServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => ClinicSlugRoute,
} as any)
const ClinicSlugReviewsRoute = ClinicSlugReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => ClinicSlugRoute,
} as any)
const ClinicSlugGalleryRoute = ClinicSlugGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => ClinicSlugRoute,
} as any)
const ClinicSlugFaqRoute = ClinicSlugFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => ClinicSlugRoute,
} as any)
const ClinicSlugContactRoute = ClinicSlugContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => ClinicSlugRoute,
} as any)
const ClinicSlugAboutRoute = ClinicSlugAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => ClinicSlugRoute,
} as any)
const ClinicSlugServicesServiceSlugRoute =
  ClinicSlugServicesServiceSlugRouteImport.update({
    id: '/$serviceSlug',
    path: '/$serviceSlug',
    getParentRoute: () => ClinicSlugServicesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/explore': typeof ExploreRoute
  '/admin/claims': typeof AdminClaimsRoute
  '/admin/clinics': typeof AdminClinicsRoute
  '/admin/import': typeof AdminImportRoute
  '/admin/themes': typeof AdminThemesRoute
  '/clinic/$slug': typeof ClinicSlugRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/clinic/$slug/about': typeof ClinicSlugAboutRoute
  '/clinic/$slug/contact': typeof ClinicSlugContactRoute
  '/clinic/$slug/faq': typeof ClinicSlugFaqRoute
  '/clinic/$slug/gallery': typeof ClinicSlugGalleryRoute
  '/clinic/$slug/reviews': typeof ClinicSlugReviewsRoute
  '/clinic/$slug/services': typeof ClinicSlugServicesRouteWithChildren
  '/clinic/$slug/smile-check': typeof ClinicSlugSmileCheckRoute
  '/clinic/$slug/': typeof ClinicSlugIndexRoute
  '/clinic/$slug/services/$serviceSlug': typeof ClinicSlugServicesServiceSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/admin/claims': typeof AdminClaimsRoute
  '/admin/clinics': typeof AdminClinicsRoute
  '/admin/import': typeof AdminImportRoute
  '/admin/themes': typeof AdminThemesRoute
  '/admin': typeof AdminIndexRoute
  '/clinic/$slug/about': typeof ClinicSlugAboutRoute
  '/clinic/$slug/contact': typeof ClinicSlugContactRoute
  '/clinic/$slug/faq': typeof ClinicSlugFaqRoute
  '/clinic/$slug/gallery': typeof ClinicSlugGalleryRoute
  '/clinic/$slug/reviews': typeof ClinicSlugReviewsRoute
  '/clinic/$slug/services': typeof ClinicSlugServicesRouteWithChildren
  '/clinic/$slug/smile-check': typeof ClinicSlugSmileCheckRoute
  '/clinic/$slug': typeof ClinicSlugIndexRoute
  '/clinic/$slug/services/$serviceSlug': typeof ClinicSlugServicesServiceSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/explore': typeof ExploreRoute
  '/admin/claims': typeof AdminClaimsRoute
  '/admin/clinics': typeof AdminClinicsRoute
  '/admin/import': typeof AdminImportRoute
  '/admin/themes': typeof AdminThemesRoute
  '/clinic/$slug': typeof ClinicSlugRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/clinic/$slug/about': typeof ClinicSlugAboutRoute
  '/clinic/$slug/contact': typeof ClinicSlugContactRoute
  '/clinic/$slug/faq': typeof ClinicSlugFaqRoute
  '/clinic/$slug/gallery': typeof ClinicSlugGalleryRoute
  '/clinic/$slug/reviews': typeof ClinicSlugReviewsRoute
  '/clinic/$slug/services': typeof ClinicSlugServicesRouteWithChildren
  '/clinic/$slug/smile-check': typeof ClinicSlugSmileCheckRoute
  '/clinic/$slug/': typeof ClinicSlugIndexRoute
  '/clinic/$slug/services/$serviceSlug': typeof ClinicSlugServicesServiceSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/explore'
    | '/admin/claims'
    | '/admin/clinics'
    | '/admin/import'
    | '/admin/themes'
    | '/clinic/$slug'
    | '/admin/'
    | '/clinic/$slug/about'
    | '/clinic/$slug/contact'
    | '/clinic/$slug/faq'
    | '/clinic/$slug/gallery'
    | '/clinic/$slug/reviews'
    | '/clinic/$slug/services'
    | '/clinic/$slug/smile-check'
    | '/clinic/$slug/'
    | '/clinic/$slug/services/$serviceSlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/explore'
    | '/admin/claims'
    | '/admin/clinics'
    | '/admin/import'
    | '/admin/themes'
    | '/admin'
    | '/clinic/$slug/about'
    | '/clinic/$slug/contact'
    | '/clinic/$slug/faq'
    | '/clinic/$slug/gallery'
    | '/clinic/$slug/reviews'
    | '/clinic/$slug/services'
    | '/clinic/$slug/smile-check'
    | '/clinic/$slug'
    | '/clinic/$slug/services/$serviceSlug'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/explore'
    | '/admin/claims'
    | '/admin/clinics'
    | '/admin/import'
    | '/admin/themes'
    | '/clinic/$slug'
    | '/admin/'
    | '/clinic/$slug/about'
    | '/clinic/$slug/contact'
    | '/clinic/$slug/faq'
    | '/clinic/$slug/gallery'
    | '/clinic/$slug/reviews'
    | '/clinic/$slug/services'
    | '/clinic/$slug/smile-check'
    | '/clinic/$slug/'
    | '/clinic/$slug/services/$serviceSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ExploreRoute: typeof ExploreRoute
  ClinicSlugRoute: typeof ClinicSlugRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/clinic/$slug': {
      id: '/clinic/$slug'
      path: '/clinic/$slug'
      fullPath: '/clinic/$slug'
      preLoaderRoute: typeof ClinicSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/themes': {
      id: '/admin/themes'
      path: '/themes'
      fullPath: '/admin/themes'
      preLoaderRoute: typeof AdminThemesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/import': {
      id: '/admin/import'
      path: '/import'
      fullPath: '/admin/import'
      preLoaderRoute: typeof AdminImportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clinics': {
      id: '/admin/clinics'
      path: '/clinics'
      fullPath: '/admin/clinics'
      preLoaderRoute: typeof AdminClinicsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/claims': {
      id: '/admin/claims'
      path: '/claims'
      fullPath: '/admin/claims'
      preLoaderRoute: typeof AdminClaimsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/clinic/$slug/': {
      id: '/clinic/$slug/'
      path: '/'
      fullPath: '/clinic/$slug/'
      preLoaderRoute: typeof ClinicSlugIndexRouteImport
      parentRoute: typeof ClinicSlugRoute
    }
    '/clinic/$slug/smile-check': {
      id: '/clinic/$slug/smile-check'
      path: '/smile-check'
      fullPath: '/clinic/$slug/smile-check'
      preLoaderRoute: typeof ClinicSlugSmileCheckRouteImport
      parentRoute: typeof ClinicSlugRoute
    }
    '/clinic/$slug/services': {
      id: '/clinic/$slug/services'
      path: '/services'
      fullPath: '/clinic/$slug/services'
      preLoaderRoute: typeof ClinicSlugServicesRouteImport
      parentRoute: typeof ClinicSlugRoute
    }
    '/clinic/$slug/reviews': {
      id: '/clinic/$slug/reviews'
      path: '/reviews'
      fullPath: '/clinic/$slug/reviews'
      preLoaderRoute: typeof ClinicSlugReviewsRouteImport
      parentRoute: typeof ClinicSlugRoute
    }
    '/clinic/$slug/gallery': {
      id: '/clinic/$slug/gallery'
      path: '/gallery'
      fullPath: '/clinic/$slug/gallery'
      preLoaderRoute: typeof ClinicSlugGalleryRouteImport
      parentRoute: typeof ClinicSlugRoute
    }
    '/clinic/$slug/faq': {
      id: '/clinic/$slug/faq'
      path: '/faq'
      fullPath: '/clinic/$slug/faq'
      preLoaderRoute: typeof ClinicSlugFaqRouteImport
      parentRoute: typeof ClinicSlugRoute
    }
    '/clinic/$slug/contact': {
      id: '/clinic/$slug/contact'
      path: '/contact'
      fullPath: '/clinic/$slug/contact'
      preLoaderRoute: typeof ClinicSlugContactRouteImport
      parentRoute: typeof ClinicSlugRoute
    }
    '/clinic/$slug/about': {
      id: '/clinic/$slug/about'
      path: '/about'
      fullPath: '/clinic/$slug/about'
      preLoaderRoute: typeof ClinicSlugAboutRouteImport
      parentRoute: typeof ClinicSlugRoute
    }
    '/clinic/$slug/services/$serviceSlug': {
      id: '/clinic/$slug/services/$serviceSlug'
      path: '/$serviceSlug'
      fullPath: '/clinic/$slug/services/$serviceSlug'
      preLoaderRoute: typeof ClinicSlugServicesServiceSlugRouteImport
      parentRoute: typeof ClinicSlugServicesRoute
    }
  }
}

interface AdminRouteChildren {
  AdminClaimsRoute: typeof AdminClaimsRoute
  AdminClinicsRoute: typeof AdminClinicsRoute
  AdminImportRoute: typeof AdminImportRoute
  AdminThemesRoute: typeof AdminThemesRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminClaimsRoute: AdminClaimsRoute,
  AdminClinicsRoute: AdminClinicsRoute,
  AdminImportRoute: AdminImportRoute,
  AdminThemesRoute: AdminThemesRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ClinicSlugServicesRouteChildren {
  ClinicSlugServicesServiceSlugRoute: typeof ClinicSlugServicesServiceSlugRoute
}

const ClinicSlugServicesRouteChildren: ClinicSlugServicesRouteChildren = {
  ClinicSlugServicesServiceSlugRoute: ClinicSlugServicesServiceSlugRoute,
}

const ClinicSlugServicesRouteWithChildren =
  ClinicSlugServicesRoute._addFileChildren(ClinicSlugServicesRouteChildren)

interface ClinicSlugRouteChildren {
  ClinicSlugAboutRoute: typeof ClinicSlugAboutRoute
  ClinicSlugContactRoute: typeof ClinicSlugContactRoute
  ClinicSlugFaqRoute: typeof ClinicSlugFaqRoute
  ClinicSlugGalleryRoute: typeof ClinicSlugGalleryRoute
  ClinicSlugReviewsRoute: typeof ClinicSlugReviewsRoute
  ClinicSlugServicesRoute: typeof ClinicSlugServicesRouteWithChildren
  ClinicSlugSmileCheckRoute: typeof ClinicSlugSmileCheckRoute
  ClinicSlugIndexRoute: typeof ClinicSlugIndexRoute
}

const ClinicSlugRouteChildren: ClinicSlugRouteChildren = {
  ClinicSlugAboutRoute: ClinicSlugAboutRoute,
  ClinicSlugContactRoute: ClinicSlugContactRoute,
  ClinicSlugFaqRoute: ClinicSlugFaqRoute,
  ClinicSlugGalleryRoute: ClinicSlugGalleryRoute,
  ClinicSlugReviewsRoute: ClinicSlugReviewsRoute,
  ClinicSlugServicesRoute: ClinicSlugServicesRouteWithChildren,
  ClinicSlugSmileCheckRoute: ClinicSlugSmileCheckRoute,
  ClinicSlugIndexRoute: ClinicSlugIndexRoute,
}

const ClinicSlugRouteWithChildren = ClinicSlugRoute._addFileChildren(
  ClinicSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ExploreRoute: ExploreRoute,
  ClinicSlugRoute: ClinicSlugRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
